# Generated by Django 3.1.4 on 2021-01-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_continousassessment_gp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continousassessment',
            old_name='gp',
            new_name='grading_point',
        ),
        migrations.AddField(
            model_name='continousassessment',
            name='quality_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
