# Generated by Django 3.1.4 on 2021-01-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20210123_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='cgpa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='gpa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
