# Generated by Django 3.1.4 on 2021-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_uploadedscoresheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
