# Generated by Django 3.1.4 on 2021-01-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_studentgrade_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
