# Generated by Django 3.1.4 on 2021-01-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_studentgrade_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedScoresheets',
        ),
    ]
