# Generated by Django 3.1.4 on 2021-01-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_delete_uploadedscoresheets'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedScoresheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
