# Generated by Django 3.1.4 on 2021-01-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAndSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FIRST_SEMESTER', 'First Semester'), ('SECOND_SEMESTER', 'Second Semester')], max_length=50, null=True)),
                ('session', models.CharField(choices=[('YEAR_1', '2020/2021 session'), ('YEAR_2', '2021/2022 session'), ('YEAR_3', '2022/2023 session'), ('YEAR_4', '2023/2024 session')], max_length=50, null=True)),
            ],
        ),
    ]
