# Generated by Django 3.1.4 on 2021-01-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionandsemester',
            name='session',
            field=models.CharField(choices=[('YEAR_1', '2020/2021 Session'), ('YEAR_2', '2021/2022 Session'), ('YEAR_3', '2022/2023 Session'), ('YEAR_4', '2023/2024 Session')], max_length=50, null=True),
        ),
    ]
