# Generated by Django 3.1.3 on 2020-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=150, null=True)),
                ('course_title', models.CharField(blank=True, max_length=150, null=True)),
                ('course_unit', models.CharField(blank=True, max_length=150, null=True)),
                ('grouping', models.CharField(choices=[('CORE', 'Core'), ('GENERAL STUDIES', 'General Studies')], default=None, max_length=100)),
            ],
        ),
    ]
