# Generated by Django 3.1.3 on 2020-12-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grouping',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('GENERAL STUDIES', 'General Studies')], default=None, max_length=100),
        ),
    ]
