# Generated by Django 3.1.4 on 2021-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
