# Generated by Django 3.1.4 on 2021-01-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201225_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='degree',
            field=models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('POSTGRADUATE', 'Postgraduate')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_images/default_dsu001.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('FACULTY OF SCIENCE', (('BIOCHEMISTRY', 'Biochemistry'), ('BOTANY', 'Botany'), ('CHEMISTRY', 'Chemistry'), ('COMPUTER_SCIENCE', 'Computer Science'), ('GEOSCIENCE', 'Geoscience'), ('MATHEMATICS', 'Mathematics'), ('MARINE_SCIENCE', 'Marine Science'), ('MICROBIOLOGY', 'Microbiology'), ('ZOOLOGY', 'Zoology'), ('PHYSICS', 'Physics'))), ('FACULTY OF ART', (('CREATIVE_ART', 'Creative Arts'), ('ENGLISH', 'English'), ('EUROPEAN_LANGUAGE', 'European Languages & Integration Studies'), ('HISTORY', 'History & Strategic Studies'), ('LINGUISTICS', 'Linguistics African Asian Studies'), ('PHILOSOPHY', 'Philosophy')))], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.CharField(choices=[('SCIENCE', 'Faculty of Science'), ('ART', 'Faculty of Arts')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman(100)'), ('SOPHOMORE', 'Sophomore(200)'), ('JUNIOR', 'Junior(300)'), ('SENIOR', 'Senior(300)')], max_length=200, null=True),
        ),
    ]
