# Generated by Django 3.1.4 on 2021-01-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210102_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_images/default_dsu001.png', upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_images/default_dsu001.png', upload_to='profile_images/'),
        ),
    ]
