# Generated by Django 3.1.4 on 2021-01-02 00:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auto_20210102_0141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='Profile',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
