# Generated by Django 3.1.4 on 2021-01-02 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210102_0146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
