# Generated by Django 3.1.4 on 2021-01-02 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='profile_images/default_dsu001.png', upload_to='profile_images/')),
                ('phone', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('reg_no', models.CharField(max_length=10, null=True)),
                ('level', models.CharField(choices=[('FRESHMAN', 'Freshman(100)'), ('SOPHOMORE', 'Sophomore(200)'), ('JUNIOR', 'Junior(300)'), ('SENIOR', 'Senior(300)')], max_length=200, null=True)),
                ('faculty', models.CharField(choices=[('SCIENCE', 'Faculty of Science'), ('ART', 'Faculty of Arts')], max_length=200, null=True)),
                ('department', models.CharField(choices=[('FACULTY OF SCIENCE', (('BIOCHEMISTRY', 'Biochemistry'), ('BOTANY', 'Botany'), ('CHEMISTRY', 'Chemistry'), ('COMPUTER_SCIENCE', 'Computer Science'), ('GEOSCIENCE', 'Geoscience'), ('MATHEMATICS', 'Mathematics'), ('MARINE_SCIENCE', 'Marine Science'), ('MICROBIOLOGY', 'Microbiology'), ('ZOOLOGY', 'Zoology'), ('PHYSICS', 'Physics'))), ('FACULTY OF ART', (('CREATIVE_ART', 'Creative Arts'), ('ENGLISH', 'English'), ('EUROPEAN_LANGUAGE', 'European Languages & Integration Studies'), ('HISTORY', 'History & Strategic Studies'), ('LINGUISTICS', 'Linguistics African Asian Studies'), ('PHILOSOPHY', 'Philosophy')))], max_length=200, null=True)),
                ('degree', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('POSTGRADUATE', 'Postgraduate')], max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
