# Generated by Django 3.1.4 on 2021-01-02 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_auto_20210102_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, choices=[('UNDERGRADUATE', 'Undergraduate'), ('POSTGRADUATE', 'Postgraduate')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('FACULTY OF SCIENCE', (('BIOCHEMISTRY', 'Biochemistry'), ('BOTANY', 'Botany'), ('CHEMISTRY', 'Chemistry'), ('COMPUTER_SCIENCE', 'Computer Science'), ('GEOSCIENCE', 'Geoscience'), ('MATHEMATICS', 'Mathematics'), ('MARINE_SCIENCE', 'Marine Science'), ('MICROBIOLOGY', 'Microbiology'), ('ZOOLOGY', 'Zoology'), ('PHYSICS', 'Physics'))), ('FACULTY OF ART', (('CREATIVE_ART', 'Creative Arts'), ('ENGLISH', 'English'), ('EUROPEAN_LANGUAGE', 'European Languages & Integration Studies'), ('HISTORY', 'History & Strategic Studies'), ('LINGUISTICS', 'Linguistics African Asian Studies'), ('PHILOSOPHY', 'Philosophy')))], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('SCIENCE', 'Faculty of Science'), ('ART', 'Faculty of Arts')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('FRESHMAN', 'Freshman(100)'), ('SOPHOMORE', 'Sophomore(200)'), ('JUNIOR', 'Junior(300)'), ('SENIOR', 'Senior(300)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reg_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
