# Generated by Django 3.1.4 on 2021-01-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='courses',
            new_name='course',
        ),
        migrations.AddField(
            model_name='timetable',
            name='date_added',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
