# Generated by Django 3.1.4 on 2021-01-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20210109_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='file',
            field=models.FileField(null=True, upload_to='timetable_files/'),
        ),
    ]
