# Generated by Django 3.1.4 on 2021-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20210109_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('SEMESTER_1', 'First Semester'), ('SEMESTER_2', 'Second Semester')], max_length=50, null=True),
        ),
    ]
