# Generated by Django 3.1.4 on 2021-01-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_timetable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='user',
        ),
    ]
