# Generated by Django 3.1.4 on 2021-01-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20210117_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.CharField(choices=[('GES', 'GES'), ('CSC', 'CSC'), ('ECON', 'ECON')], max_length=50, null=True),
        ),
    ]
