# Generated by Django 3.1.4 on 2021-01-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20210117_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.CharField(choices=[('CSC', 'CSC'), ('ECON', 'ECON'), ('GES', 'GES'), ('MTH', 'MTH'), ('BIS', 'BIS'), ('NUT', 'NUT'), ('ART', 'ART')], max_length=50, null=True),
        ),
    ]
