# Generated by Django 3.1.3 on 2020-12-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('post', models.TextField()),
                ('thumbnail', models.ImageField(default='posts/default.jpg', upload_to='posts/')),
            ],
        ),
    ]
