# Generated by Django 3.1.3 on 2020-12-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_creation', '0002_createpost_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='summary',
        ),
    ]
