# Generated by Django 3.1.3 on 2020-12-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_creation', '0003_remove_createpost_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatePost',
            new_name='Post',
        ),
    ]
