# Generated by Django 3.1.3 on 2020-12-24 21:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_creation', '0004_auto_20201224_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
